# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171007_1716_squashed_0006_auto_20171008_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
